version: 2
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/src-tauri" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "dev"
    reviewers:
      - "ahadley1124"